Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  
      config.vm.define "arakhursS" do |master|
        master.vm.hostname = "k3s-master"
        master.vm.network "private_network", ip: "192.168.56.110"
        master.vm.provider "virtualbox" do |sv|
          sv.name = "master"
        end
        master.vm.provision "shell", path: "scripts/k3s-master.sh"
      end
  end
  