Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  # worker.vm.provider "virtualbox" do |vb|
  #   vb.memory = "1024"
  #   vb.cpus = 2
  # end
    
    config.vm.define "arakhursS" do |master|
      master.vm.hostname = "k3s-master"
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      master.vm.provision "shell", path: "scripts/k3s-master.sh"
    end
    
    config.vm.define "arakhursSW" do |worker|
      worker.vm.hostname = "k3s-worker"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
      end
      worker.vm.provision "shell", path: "scripts/k3s-worker.sh", args: ["192.168.56.110"]

    end
end
